# Generated by Django 3.1.7 on 2021-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField(blank=True, null=True, verbose_name='Alias')),
                ('target', models.CharField(blank=True, max_length=24, null=True, verbose_name='Slug')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End')),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Alias',
            },
        ),
    ]
